### ISSUE TITLE
Don't know why path 'C:/Users/Raj Shah/Downloads/AHD_Project' still exists somewhere after replaced

### ISSUE THREAD

**Issue by stephencheung16** [raj-shah14/Hand-Gesture-Recognition-Using-CNN#2]
Hi Raj Shah,

I tried to run predictgest.py.  I noticed the absolute path is used in

saver = tf.train.import_meta_graph('C:/Users/Raj Shah/Downloads/AHD_Project/handgest_1.meta')

so I replaced it by my my own path.  But I still got the error related to the path 'C:/Users/Raj Sah/Downloads/AHD_Project' as follows:

Traceback (most recent call last):
  File "predictgest.py", line 22, in <module>
    saver.restore(sess, tf.train.latest_checkpoint('./'))
  File "/home/cheunghk/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1602, in latest_checkpoint
    if file_io.get_matching_files(v2_path) or file_io.get_matching_files(
  File "/home/cheunghk/tensorflow/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 332, in get_matching_files
    for single_filename in filename
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/cheunghk/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: ./C:/Users/Raj Shah/Downloads/AHD_Project

It seems the path '/C:/Users/Raj Shah/Downloads/AHD_Project' still exists somewhere, probably in the checkpoint or the graph.

Would you please help?  Thanks.

Regards,
Stephen

**Comment by stephencheung16** [comment]
Oh, I have fixed it.  The path exists in the file 'checkpoint'.  I have replaced it with my own path.

Regards,
Stephen
